### ISSUE TITLE
Help for running the example

### ISSUE THREAD

**Issue by fabriziopandini** [wapc/wapc-go#4] opened 2021-05-15 20:35 UTC
Hi all!
I'm trying to run the example from https://github.com/wapc/wapc-go#example with a wasm module built in go using https://github.com/wapc/wapc-guest-tinygo#example

But I get 

```
panic: Failed to instantiate the module:
    link error: Import not found, namespace: wasi_snapshot_preview1, name: fd_write
```

Any hint will be super appreciated

**Comment by alanpoon** [comment] 2021-06-03 02:34
Your error log is not full. Mine is Import not found, namespace: env
![image](https://user-images.githubusercontent.com/8205468/120577628-29f43080-c457-11eb-828d-5f204477d5cc.png)

**Comment by venjiang** [comment] 2021-06-11 16:41
same issue.

**Comment by alanpoon** [comment] 2021-06-12 06:54
You have to either use tiny-go version earlier than 0.18. or you convert the wasm to wat. String replace "wasi_snapshot_preview1" to "wasi-unstable" then convert it back to wasm. This repo is quite outdated, will need to change to depend on wasm3

**Comment by venjiang** [comment] 2021-07-09 04:38
still maintained?

**Comment by pkedy** [comment] 2021-07-22 23:42
I am working on upgrading to the latest [Wasmer Go library](https://github.com/wasmerio/wasmer-go) to resolve this. There many breaking changes in the API but I hope to have it working soon.

**Comment by fabriziopandini** [comment] 2021-07-23 08:22
Great news @pkedy!
Whenever I can give a try, ping me!

**Comment by pkedy** [comment] 2021-07-25 15:24
An update on upgrading to the latest `wasmer-go`:
I have a branch for the latest library here: https://github.com/wapc/wapc-go/tree/wasmer_v1.0.3
Unfortunately, after a handful of invocations to a module, I get a panic from `wasmer-go`.

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/714039/126904352-81acff21-2a33-4929-a703-5a13dda7a158.png">

I'm still looking into it but it feels like an issue in `wasmer-go`. If I can narrow it down, I'll submit an issue/PR to `wasmer-go`. If not, this might be reason to switch to Wasmtime's Go library.

**Comment by pkedy** [comment] 2021-07-25 16:22
I may have figured it out. My hypothesis is that the waPC Instance needs to prevent the instances of `*wasmer.Function/wasmer.IntoExtern` from being garbage collected. I've committed the change. Tests are looking good so far.

**Comment by pkedy** [comment] 2021-07-26 19:57
[This branch](https://github.com/wapc/wapc-go/tree/wasmer_v1.0.3) with Wasmer v1.0.3 seems to be working well and I'm considering opening a PR.

@fabriziopandini @madflojo Do you think you could test it out?

**Comment by madflojo** [comment] 2021-07-26 21:28
@pkedy, I merged my Go testdata changes with your new branch on my fork https://github.com/madflojo/wapc-go/tree/wasmer_v1.0.3/testdata/go and tested it.

With TinyGo v0.17.0 - works well from what I can see (non-breaking).
With TinyGo v0.19.0 - Got the below Error.

```console
$ go test -v ./...
=== RUN   TestModule
--- PASS: TestModule (0.01s)
=== RUN   TestPool
    pool_test.go:29: 
                Error Trace:    pool_test.go:29
                Error:          Received unexpected error:
                                Missing import: `wasi_snapshot_preview1`.`args_sizes_get`
                Test:           TestPool
--- FAIL: TestPool (0.04s)
FAIL
FAIL    github.com/wapc/wapc-go 0.242s
?       github.com/wapc/wapc-go/example [no test files]
FAIL
```

I also created a branch on my main project that uses wapc-go https://github.com/madflojo/tarmac/tree/wapc-wasmer and updated it to the new branch. With `testdata/scheduler.wasm` being TinyGo v0.17.0 and `testdata/tarmac.wasm` being TinyGo v0.19.0. The results are the same, v0.17.0 works great, v0.19.0 has the same import error.

Looks like you are close to working!

**Comment by pkedy** [comment] 2021-07-26 21:49
@madflojo Are you compiling using target `wasi` instead of `wasm`?  If so, please try `wasm`. I've noticed that `wasm` only requires `fd_write` where `wasi` requires a few more functions.

If `wasm` works for you, I'll create the PR and do some follow up research for the `wasi` target.

**Comment by pkedy** [comment] 2021-07-27 01:12
Actually, I added `args_sizes_get` and `args_get` to support TinyGo `-target wasi`. My feeling is that `-target wasm` is sufficient for waPC but give it a test.

**Comment by madflojo** [comment] 2021-07-27 01:14
Let me test out the latest, FYI targeting `wasm` I am getting this error:

```console
=== RUN   TestPool
    pool_test.go:29: 
                Error Trace:    pool_test.go:29
                Error:          Received unexpected error:
                                Missing import: `env`.`syscall/js.valueGet`
                Test:           TestPool
```

If I remember right (and I couldn't find it referenced anywhere) when I was playing with wasmer-go in the past I had a hard time getting any Go compiled code to work that wasn't for WASI.

**Comment by pkedy** [comment] 2021-07-27 01:19
Weird. `syscall/js.*` are definitely imported if you are using Go and not TinyGo. Your program must be importing some package that requires that. Never seen that with TinyGo.

**Comment by madflojo** [comment] 2021-07-27 01:33
The only thing that code is importing outside of the wapc go client is `fmt`. It maybe a TinyGo thing with `fmt`.

On the `wasi` front, so the same code untouched compiled in v0.17.0 works great no issues. 

```console
$ docker run -v `pwd`:/build -w /build tinygo/tinygo:0.17.0  tinygo build -o /build/hello.wasm -target wasi /build/main.go
go: downloading github.com/wapc/wapc-guest-tinygo v0.3.0
$ cd ../../
$ go test -v ./...
=== RUN   TestModule
--- PASS: TestModule (0.01s)
=== RUN   TestPool
--- PASS: TestPool (0.04s)
PASS
ok      github.com/wapc/wapc-go 0.307s
?       github.com/wapc/wapc-go/example [no test files]
```

But v0.19.0 seems to be running into some sort of error (though not specific what).

```console
$ docker run -v `pwd`:/build -w /build tinygo/tinygo:0.19.0  tinygo build -o /build/hello.wasm -target wasi /build/main.go
go: downloading github.com/wapc/wapc-guest-tinygo v0.3.0
$ cd ../../
$ go test -v ./...
=== RUN   TestModule
--- PASS: TestModule (0.02s)
=== RUN   TestPool
    pool_test.go:37: 
                Error Trace:    pool_test.go:37
                Error:          Received unexpected error:
                                call to "hello" was unsuccessful
                Test:           TestPool
--- FAIL: TestPool (0.06s)
FAIL
FAIL    github.com/wapc/wapc-go 0.285s
?       github.com/wapc/wapc-go/example [no test files]
FAIL
```

**Comment by pkedy** [comment] 2021-07-27 01:38
Thanks! That's very helpful. I'll look into this more tomorrow.

You might also want to try this release of the guest library. https://github.com/wapc/wapc-guest-tinygo/releases/tag/v0.3.1

**Comment by madflojo** [comment] 2021-07-29 17:20
@pkedy just got around to testing the v0.3.1 version as you suggested and it took care of the error I was getting.

```console
$ go test -v ./...
=== RUN   TestModule
--- PASS: TestModule (0.01s)
=== RUN   TestPool
--- PASS: TestPool (0.04s)
PASS
ok      github.com/wapc/wapc-go 0.232s
?       github.com/wapc/wapc-go/example [no test files]
```

I also tested with my other project but did get some errors there. I'll keep testing and let you know.

**Comment by pkedy** [comment] 2021-07-29 19:51
Awesome.  And I confirmed what you said that importing `fmt` targeting `wasm` instead of `wasi` creates all the JS imports we don't want. So perhaps `-target wasi` is preferred. At least until `0.20.0` when it all changes again :)

**Comment by madflojo** [comment] 2021-07-29 21:54
Ok, I did some testing against TinyGo 0.17.0, 0.19.0 and Rust and things are looking good to me.
```
tests_1              | --- PASS: TestWASMExecutionPortability (0.74s)
tests_1              |     --- PASS: TestWASMExecutionPortability/Verify_-_/testdata/tinygo19.wasm (0.19s)
tests_1              |     --- PASS: TestWASMExecutionPortability/Verify_-_/testdata/tinygo17.wasm (0.28s)
tests_1              |     --- PASS: TestWASMExecutionPortability/Verify_-_/testdata/rust.wasm (0.27s)
```

**Comment by pkedy** [comment] 2021-07-30 20:08
@madflojo That's great news! I've also tested TinyGo and AssemblyScript extensively. Based on this, I created #6. Feel free to review. I'll merge and cut a new release later today or early tomorrow.

**Comment by fabriziopandini** [comment] 2021-08-01 09:43
@pkedy thanks for all your work!
I have made some tests and thanks to your work I'm now unblocked for my experiments when working with the following configuration:

guest (the WebAssembly) with  
> github.com/wapc/wapc-guest-tinygo v0.3.1 
> build with tinygo v0:18 --target wasi

server with
> github.com/wapc/wapc-go v0.3.0  

FYI, when building with tinygo v0:19 --target wasi, instead I got an error server side.

Note: it will be great if this repository gets a go example under testdata instead of a typescript one

**Comment by pkedy** [comment] 2022-05-29 21:48
@fabriziopandini That's great! Please reopen if you need anything else

**Closed by pkedy** 2022-05-29 21:48 UTC
